name: Lint

on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  lint-bash:
    name: Lint Bash scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: shellcheck
          level: warning
          path: .
          pattern: '*.sh'
          fail_on_error: true

  lint-dockerfile:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          level: warning
          fail_on_error: true
          hadolint_ignore: DL3016 DL3018 # Ignore pinning apk and npm packages to specific version with @
